name: i_sense_lab_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # ai_awesome_message: ^0.3.0
  # pinput: ^1.0.0
  flutter_login: ^1.0.14
  flutter_svg_provider: ^0.1.8
  animated_text_kit: ^3.1.0
  flutter_blue: ^0.7.3
  getwidget: ^1.2.4
  bot_toast: ^3.0.5
  cool_alert: ^1.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/hands_background.png
    - images/compute_icon.png
    - images/orientation_icon.png
    - images/memorization_icon.png
    - images/naming_icon.png
    - images/concentration_icon.png
    - images/drawing_icon.png
    - images/abstract_icon.png
    - images/login_logo.png
    - images/heart_icon.png
    - images/undefined.png
    - images/orientation/season_spring_icon.png
    - images/orientation/season_summer_icon.png
    - images/orientation/season_autumn_icon.png
    - images/orientation/season_winter_icon.png
    - images/orientation/season_spring.png
    - images/orientation/season_summer.png
    - images/orientation/season_autumn.png
    - images/orientation/season_winter.png
    - images/compute/background.jpg
    - images/feedback/star_blue.png
    - images/feedback/star_green.png
    - images/feedback/star_grey.png
    - images/feedback/star_purple.png
    - images/feedback/star_red.png
    - images/feedback/star_yellow.png
    - images/feedback/star_red_cross.png
    - images/feedback/animated/crying_moon.gif
    - images/feedback/animated/cheer_animated.gif
    - images/feedback/animated/firework1_animated.gif
    - images/feedback/animated/firework2_animated.gif
    - images/feedback/animated/firework3_animated.gif
    - images/feedback/animated/leaves_animated.gif
    - images/feedback/animated/love_animated.gif
    - images/feedback/animated/rainbow_animated.gif
    - images/feedback/animated/sparkle_animated.gif
    - images/main_pics/cheer2.png
    - images/main_pics/cheer3.png
    - images/main_pics/cheer4.png
    - images/main_pics/naxsen.png
    - images/main_pics/naxsen300.png
    - images/main_pics/naxsen300_resized.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
